// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: lineage-studio.proto

package lineage_studio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseType int32

const (
	DatabaseType_DATABASE_TYPE_UNSPECIFIED DatabaseType = 0
	DatabaseType_DATABASE_TYPE_MSSQL       DatabaseType = 1
	DatabaseType_DATABASE_TYPE_ORACLE      DatabaseType = 2
)

// Enum value maps for DatabaseType.
var (
	DatabaseType_name = map[int32]string{
		0: "DATABASE_TYPE_UNSPECIFIED",
		1: "DATABASE_TYPE_MSSQL",
		2: "DATABASE_TYPE_ORACLE",
	}
	DatabaseType_value = map[string]int32{
		"DATABASE_TYPE_UNSPECIFIED": 0,
		"DATABASE_TYPE_MSSQL":       1,
		"DATABASE_TYPE_ORACLE":      2,
	}
)

func (x DatabaseType) Enum() *DatabaseType {
	p := new(DatabaseType)
	*p = x
	return p
}

func (x DatabaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_lineage_studio_proto_enumTypes[0].Descriptor()
}

func (DatabaseType) Type() protoreflect.EnumType {
	return &file_lineage_studio_proto_enumTypes[0]
}

func (x DatabaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseType.Descriptor instead.
func (DatabaseType) EnumDescriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{0}
}

type ObjectType int32

const (
	ObjectType_OBJECT_TYPE_UNSPECIFIED ObjectType = 0
	ObjectType_OBJECT_TYPE_VIEW        ObjectType = 1
	ObjectType_OBJECT_TYPE_PROCEDURE   ObjectType = 2
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIED",
		1: "OBJECT_TYPE_VIEW",
		2: "OBJECT_TYPE_PROCEDURE",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIED": 0,
		"OBJECT_TYPE_VIEW":        1,
		"OBJECT_TYPE_PROCEDURE":   2,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_lineage_studio_proto_enumTypes[1].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_lineage_studio_proto_enumTypes[1]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{1}
}

type WriteStatus int32

const (
	WriteStatus_WRITE_STATUS_UNSPECIFIED WriteStatus = 0
	WriteStatus_WRITE_STATUS_OK          WriteStatus = 1
	WriteStatus_WRITE_STATUS_CONFLICT    WriteStatus = 2
	WriteStatus_WRITE_STATUS_DENIED      WriteStatus = 3
)

// Enum value maps for WriteStatus.
var (
	WriteStatus_name = map[int32]string{
		0: "WRITE_STATUS_UNSPECIFIED",
		1: "WRITE_STATUS_OK",
		2: "WRITE_STATUS_CONFLICT",
		3: "WRITE_STATUS_DENIED",
	}
	WriteStatus_value = map[string]int32{
		"WRITE_STATUS_UNSPECIFIED": 0,
		"WRITE_STATUS_OK":          1,
		"WRITE_STATUS_CONFLICT":    2,
		"WRITE_STATUS_DENIED":      3,
	}
)

func (x WriteStatus) Enum() *WriteStatus {
	p := new(WriteStatus)
	*p = x
	return p
}

func (x WriteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lineage_studio_proto_enumTypes[2].Descriptor()
}

func (WriteStatus) Type() protoreflect.EnumType {
	return &file_lineage_studio_proto_enumTypes[2]
}

func (x WriteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStatus.Descriptor instead.
func (WriteStatus) EnumDescriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{2}
}

type RepoSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DatabaseType DatabaseType           `protobuf:"varint,2,opt,name=database_type,json=databaseType,proto3,enum=DatabaseType" json:"database_type,omitempty"`
	Host         string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	DbName       string                 `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	RepoVersion  string                 `protobuf:"bytes,5,opt,name=repo_version,json=repoVersion,proto3" json:"repo_version,omitempty"`
	LastSyncedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"`
}

func (x *RepoSummary) Reset() {
	*x = RepoSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoSummary) ProtoMessage() {}

func (x *RepoSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoSummary.ProtoReflect.Descriptor instead.
func (*RepoSummary) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{0}
}

func (x *RepoSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepoSummary) GetDatabaseType() DatabaseType {
	if x != nil {
		return x.DatabaseType
	}
	return DatabaseType_DATABASE_TYPE_UNSPECIFIED
}

func (x *RepoSummary) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RepoSummary) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *RepoSummary) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

func (x *RepoSummary) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncedAt
	}
	return nil
}

type ObjectSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ObjectType ObjectType `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3,enum=ObjectType" json:"object_type,omitempty"`
	Verified   bool       `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *ObjectSummary) Reset() {
	*x = ObjectSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSummary) ProtoMessage() {}

func (x *ObjectSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSummary.ProtoReflect.Descriptor instead.
func (*ObjectSummary) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectSummary) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *ObjectSummary) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type ObjectDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ObjectType  ObjectType             `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3,enum=ObjectType" json:"object_type,omitempty"`
	SourceCode  string                 `protobuf:"bytes,3,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Lineage     string                 `protobuf:"bytes,4,opt,name=lineage,proto3" json:"lineage,omitempty"`
	LineageHash string                 `protobuf:"bytes,5,opt,name=lineage_hash,json=lineageHash,proto3" json:"lineage_hash,omitempty"`
	ObjectHash  string                 `protobuf:"bytes,6,opt,name=object_hash,json=objectHash,proto3" json:"object_hash,omitempty"`
	Verified    bool                   `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VerifiedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	RepoVersion string                 `protobuf:"bytes,10,opt,name=repo_version,json=repoVersion,proto3" json:"repo_version,omitempty"`
}

func (x *ObjectDetail) Reset() {
	*x = ObjectDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDetail) ProtoMessage() {}

func (x *ObjectDetail) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDetail.ProtoReflect.Descriptor instead.
func (*ObjectDetail) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectDetail) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *ObjectDetail) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ObjectDetail) GetLineage() string {
	if x != nil {
		return x.Lineage
	}
	return ""
}

func (x *ObjectDetail) GetLineageHash() string {
	if x != nil {
		return x.LineageHash
	}
	return ""
}

func (x *ObjectDetail) GetObjectHash() string {
	if x != nil {
		return x.ObjectHash
	}
	return ""
}

func (x *ObjectDetail) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *ObjectDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectDetail) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *ObjectDetail) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

type HistoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectHash string                 `protobuf:"bytes,1,opt,name=object_hash,json=objectHash,proto3" json:"object_hash,omitempty"`
	Verified   bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryEntry) GetObjectHash() string {
	if x != nil {
		return x.ObjectHash
	}
	return ""
}

func (x *HistoryEntry) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *HistoryEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ConflictDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentRepoVersion string        `protobuf:"bytes,1,opt,name=current_repo_version,json=currentRepoVersion,proto3" json:"current_repo_version,omitempty"`
	CurrentObject      *ObjectDetail `protobuf:"bytes,2,opt,name=current_object,json=currentObject,proto3" json:"current_object,omitempty"`
}

func (x *ConflictDetail) Reset() {
	*x = ConflictDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConflictDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictDetail) ProtoMessage() {}

func (x *ConflictDetail) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictDetail.ProtoReflect.Descriptor instead.
func (*ConflictDetail) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{4}
}

func (x *ConflictDetail) GetCurrentRepoVersion() string {
	if x != nil {
		return x.CurrentRepoVersion
	}
	return ""
}

func (x *ConflictDetail) GetCurrentObject() *ObjectDetail {
	if x != nil {
		return x.CurrentObject
	}
	return nil
}

type GetReposRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReposRequest) Reset() {
	*x = GetReposRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposRequest) ProtoMessage() {}

func (x *GetReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposRequest.ProtoReflect.Descriptor instead.
func (*GetReposRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{5}
}

type GetReposResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repos []*RepoSummary `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
}

func (x *GetReposResponse) Reset() {
	*x = GetReposResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposResponse) ProtoMessage() {}

func (x *GetReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposResponse.ProtoReflect.Descriptor instead.
func (*GetReposResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{6}
}

func (x *GetReposResponse) GetRepos() []*RepoSummary {
	if x != nil {
		return x.Repos
	}
	return nil
}

type GetObjectsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
}

func (x *GetObjectsRequest) Reset() {
	*x = GetObjectsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsRequest) ProtoMessage() {}

func (x *GetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsRequest.ProtoReflect.Descriptor instead.
func (*GetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectsRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

type GetObjectsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoVersion string           `protobuf:"bytes,1,opt,name=repo_version,json=repoVersion,proto3" json:"repo_version,omitempty"`
	Objects     []*ObjectSummary `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *GetObjectsResponse) Reset() {
	*x = GetObjectsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsResponse) ProtoMessage() {}

func (x *GetObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsResponse.ProtoReflect.Descriptor instead.
func (*GetObjectsResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{8}
}

func (x *GetObjectsResponse) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

func (x *GetObjectsResponse) GetObjects() []*ObjectSummary {
	if x != nil {
		return x.Objects
	}
	return nil
}

type GetObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName   string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	ObjectName string `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	// optional , empty mean it is current hash
	HistoryHash string `protobuf:"bytes,3,opt,name=history_hash,json=historyHash,proto3" json:"history_hash,omitempty"`
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{9}
}

func (x *GetObjectRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *GetObjectRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *GetObjectRequest) GetHistoryHash() string {
	if x != nil {
		return x.HistoryHash
	}
	return ""
}

type GetObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object       *ObjectDetail `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	IsHistorical bool          `protobuf:"varint,2,opt,name=is_historical,json=isHistorical,proto3" json:"is_historical,omitempty"`
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{10}
}

func (x *GetObjectResponse) GetObject() *ObjectDetail {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GetObjectResponse) GetIsHistorical() bool {
	if x != nil {
		return x.IsHistorical
	}
	return false
}

type GetObjectHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName   string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	ObjectName string `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
}

func (x *GetObjectHistoryRequest) Reset() {
	*x = GetObjectHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectHistoryRequest) ProtoMessage() {}

func (x *GetObjectHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetObjectHistoryRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{11}
}

func (x *GetObjectHistoryRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *GetObjectHistoryRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type GetObjectHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Histories []*HistoryEntry `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
}

func (x *GetObjectHistoryResponse) Reset() {
	*x = GetObjectHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectHistoryResponse) ProtoMessage() {}

func (x *GetObjectHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetObjectHistoryResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{12}
}

func (x *GetObjectHistoryResponse) GetHistories() []*HistoryEntry {
	if x != nil {
		return x.Histories
	}
	return nil
}

type RefreshRepoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
}

func (x *RefreshRepoRequest) Reset() {
	*x = RefreshRepoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRepoRequest) ProtoMessage() {}

func (x *RefreshRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRepoRequest.ProtoReflect.Descriptor instead.
func (*RefreshRepoRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshRepoRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

type RefreshRepoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewRepoVersion string `protobuf:"bytes,1,opt,name=new_repo_version,json=newRepoVersion,proto3" json:"new_repo_version,omitempty"`
	HadChanges     bool   `protobuf:"varint,2,opt,name=had_changes,json=hadChanges,proto3" json:"had_changes,omitempty"`
}

func (x *RefreshRepoResponse) Reset() {
	*x = RefreshRepoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRepoResponse) ProtoMessage() {}

func (x *RefreshRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRepoResponse.ProtoReflect.Descriptor instead.
func (*RefreshRepoResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshRepoResponse) GetNewRepoVersion() string {
	if x != nil {
		return x.NewRepoVersion
	}
	return ""
}

func (x *RefreshRepoResponse) GetHadChanges() bool {
	if x != nil {
		return x.HadChanges
	}
	return false
}

type VerifyObjectLineageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName    string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	ObjectName  string `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	RepoVersion string `protobuf:"bytes,3,opt,name=repo_version,json=repoVersion,proto3" json:"repo_version,omitempty"`
}

func (x *VerifyObjectLineageRequest) Reset() {
	*x = VerifyObjectLineageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyObjectLineageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyObjectLineageRequest) ProtoMessage() {}

func (x *VerifyObjectLineageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyObjectLineageRequest.ProtoReflect.Descriptor instead.
func (*VerifyObjectLineageRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyObjectLineageRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *VerifyObjectLineageRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *VerifyObjectLineageRequest) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

type VerifyObjectLineageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         WriteStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=WriteStatus" json:"status,omitempty"`
	NewRepoVersion string          `protobuf:"bytes,2,opt,name=new_repo_version,json=newRepoVersion,proto3" json:"new_repo_version,omitempty"`
	Conflict       *ConflictDetail `protobuf:"bytes,3,opt,name=conflict,proto3" json:"conflict,omitempty"`
}

func (x *VerifyObjectLineageResponse) Reset() {
	*x = VerifyObjectLineageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyObjectLineageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyObjectLineageResponse) ProtoMessage() {}

func (x *VerifyObjectLineageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyObjectLineageResponse.ProtoReflect.Descriptor instead.
func (*VerifyObjectLineageResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyObjectLineageResponse) GetStatus() WriteStatus {
	if x != nil {
		return x.Status
	}
	return WriteStatus_WRITE_STATUS_UNSPECIFIED
}

func (x *VerifyObjectLineageResponse) GetNewRepoVersion() string {
	if x != nil {
		return x.NewRepoVersion
	}
	return ""
}

func (x *VerifyObjectLineageResponse) GetConflict() *ConflictDetail {
	if x != nil {
		return x.Conflict
	}
	return nil
}

type ChangeLineageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName    string `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	ObjectName  string `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Lineage     string `protobuf:"bytes,3,opt,name=lineage,proto3" json:"lineage,omitempty"`
	RepoVersion string `protobuf:"bytes,4,opt,name=repo_version,json=repoVersion,proto3" json:"repo_version,omitempty"`
}

func (x *ChangeLineageRequest) Reset() {
	*x = ChangeLineageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeLineageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLineageRequest) ProtoMessage() {}

func (x *ChangeLineageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLineageRequest.ProtoReflect.Descriptor instead.
func (*ChangeLineageRequest) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeLineageRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *ChangeLineageRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *ChangeLineageRequest) GetLineage() string {
	if x != nil {
		return x.Lineage
	}
	return ""
}

func (x *ChangeLineageRequest) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

type ChangeLineageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         WriteStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=WriteStatus" json:"status,omitempty"`
	NewRepoVersion string          `protobuf:"bytes,2,opt,name=new_repo_version,json=newRepoVersion,proto3" json:"new_repo_version,omitempty"`
	UpdatedObject  *ObjectDetail   `protobuf:"bytes,3,opt,name=updated_object,json=updatedObject,proto3" json:"updated_object,omitempty"`
	Conflict       *ConflictDetail `protobuf:"bytes,4,opt,name=conflict,proto3" json:"conflict,omitempty"`
}

func (x *ChangeLineageResponse) Reset() {
	*x = ChangeLineageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_studio_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeLineageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLineageResponse) ProtoMessage() {}

func (x *ChangeLineageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_studio_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLineageResponse.ProtoReflect.Descriptor instead.
func (*ChangeLineageResponse) Descriptor() ([]byte, []int) {
	return file_lineage_studio_proto_rawDescGZIP(), []int{18}
}

func (x *ChangeLineageResponse) GetStatus() WriteStatus {
	if x != nil {
		return x.Status
	}
	return WriteStatus_WRITE_STATUS_UNSPECIFIED
}

func (x *ChangeLineageResponse) GetNewRepoVersion() string {
	if x != nil {
		return x.NewRepoVersion
	}
	return ""
}

func (x *ChangeLineageResponse) GetUpdatedObject() *ObjectDetail {
	if x != nil {
		return x.UpdatedObject
	}
	return nil
}

func (x *ChangeLineageResponse) GetConflict() *ConflictDetail {
	if x != nil {
		return x.Conflict
	}
	return nil
}

var File_lineage_studio_proto protoreflect.FileDescriptor

var file_lineage_studio_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x0d, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x40, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x6d, 0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x22, 0x86, 0x03, 0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x86, 0x01, 0x0a, 0x0c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x78, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x11, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x05, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x22, 0x30, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x70, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x73, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x5f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x73, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63,
	0x61, 0x6c, 0x22, 0x57, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x12, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52,
	0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x70, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x13, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x10, 0x6e, 0x65, 0x77, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x52, 0x65, 0x70,
	0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x64, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68,
	0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x7d, 0x0a, 0x1a, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70,
	0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x9a, 0x01, 0x0a, 0x1b, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28,
	0x0a, 0x10, 0x6e, 0x65, 0x77, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x52, 0x65, 0x70,
	0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x66,
	0x6c, 0x69, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x6c, 0x69, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x66, 0x6c, 0x69, 0x63, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xca, 0x01, 0x0a, 0x15, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x65, 0x77,
	0x5f, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x52, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x66, 0x6c, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x2a, 0x60, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41,
	0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41, 0x53,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x53, 0x53, 0x51, 0x4c, 0x10, 0x01, 0x12, 0x18,
	0x0a, 0x14, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4f, 0x52, 0x41, 0x43, 0x4c, 0x45, 0x10, 0x02, 0x2a, 0x5a, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x44, 0x55,
	0x52, 0x45, 0x10, 0x02, 0x2a, 0x74, 0x0a, 0x0b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x4c, 0x49, 0x43, 0x54, 0x10,
	0x02, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x03, 0x32, 0xc7, 0x03, 0x0a, 0x14, 0x4c,
	0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x12,
	0x10, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x50, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lineage_studio_proto_rawDescOnce sync.Once
	file_lineage_studio_proto_rawDescData = file_lineage_studio_proto_rawDesc
)

func file_lineage_studio_proto_rawDescGZIP() []byte {
	file_lineage_studio_proto_rawDescOnce.Do(func() {
		file_lineage_studio_proto_rawDescData = protoimpl.X.CompressGZIP(file_lineage_studio_proto_rawDescData)
	})
	return file_lineage_studio_proto_rawDescData
}

var file_lineage_studio_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lineage_studio_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lineage_studio_proto_goTypes = []interface{}{
	(DatabaseType)(0),                   // 0: DatabaseType
	(ObjectType)(0),                     // 1: ObjectType
	(WriteStatus)(0),                    // 2: WriteStatus
	(*RepoSummary)(nil),                 // 3: RepoSummary
	(*ObjectSummary)(nil),               // 4: ObjectSummary
	(*ObjectDetail)(nil),                // 5: ObjectDetail
	(*HistoryEntry)(nil),                // 6: HistoryEntry
	(*ConflictDetail)(nil),              // 7: ConflictDetail
	(*GetReposRequest)(nil),             // 8: GetReposRequest
	(*GetReposResponse)(nil),            // 9: GetReposResponse
	(*GetObjectsRequest)(nil),           // 10: GetObjectsRequest
	(*GetObjectsResponse)(nil),          // 11: GetObjectsResponse
	(*GetObjectRequest)(nil),            // 12: GetObjectRequest
	(*GetObjectResponse)(nil),           // 13: GetObjectResponse
	(*GetObjectHistoryRequest)(nil),     // 14: GetObjectHistoryRequest
	(*GetObjectHistoryResponse)(nil),    // 15: GetObjectHistoryResponse
	(*RefreshRepoRequest)(nil),          // 16: RefreshRepoRequest
	(*RefreshRepoResponse)(nil),         // 17: RefreshRepoResponse
	(*VerifyObjectLineageRequest)(nil),  // 18: VerifyObjectLineageRequest
	(*VerifyObjectLineageResponse)(nil), // 19: VerifyObjectLineageResponse
	(*ChangeLineageRequest)(nil),        // 20: ChangeLineageRequest
	(*ChangeLineageResponse)(nil),       // 21: ChangeLineageResponse
	(*timestamppb.Timestamp)(nil),       // 22: google.protobuf.Timestamp
}
var file_lineage_studio_proto_depIdxs = []int32{
	0,  // 0: RepoSummary.database_type:type_name -> DatabaseType
	22, // 1: RepoSummary.last_synced_at:type_name -> google.protobuf.Timestamp
	1,  // 2: ObjectSummary.object_type:type_name -> ObjectType
	1,  // 3: ObjectDetail.object_type:type_name -> ObjectType
	22, // 4: ObjectDetail.created_at:type_name -> google.protobuf.Timestamp
	22, // 5: ObjectDetail.verified_at:type_name -> google.protobuf.Timestamp
	22, // 6: HistoryEntry.created_at:type_name -> google.protobuf.Timestamp
	5,  // 7: ConflictDetail.current_object:type_name -> ObjectDetail
	3,  // 8: GetReposResponse.repos:type_name -> RepoSummary
	4,  // 9: GetObjectsResponse.objects:type_name -> ObjectSummary
	5,  // 10: GetObjectResponse.object:type_name -> ObjectDetail
	6,  // 11: GetObjectHistoryResponse.histories:type_name -> HistoryEntry
	2,  // 12: VerifyObjectLineageResponse.status:type_name -> WriteStatus
	7,  // 13: VerifyObjectLineageResponse.conflict:type_name -> ConflictDetail
	2,  // 14: ChangeLineageResponse.status:type_name -> WriteStatus
	5,  // 15: ChangeLineageResponse.updated_object:type_name -> ObjectDetail
	7,  // 16: ChangeLineageResponse.conflict:type_name -> ConflictDetail
	8,  // 17: LineageStudioService.GetRepos:input_type -> GetReposRequest
	10, // 18: LineageStudioService.GetObjects:input_type -> GetObjectsRequest
	12, // 19: LineageStudioService.GetObject:input_type -> GetObjectRequest
	14, // 20: LineageStudioService.GetObjectHistory:input_type -> GetObjectHistoryRequest
	16, // 21: LineageStudioService.RefreshRepo:input_type -> RefreshRepoRequest
	18, // 22: LineageStudioService.VerifyObjectLineage:input_type -> VerifyObjectLineageRequest
	20, // 23: LineageStudioService.ChangeLineage:input_type -> ChangeLineageRequest
	9,  // 24: LineageStudioService.GetRepos:output_type -> GetReposResponse
	11, // 25: LineageStudioService.GetObjects:output_type -> GetObjectsResponse
	13, // 26: LineageStudioService.GetObject:output_type -> GetObjectResponse
	15, // 27: LineageStudioService.GetObjectHistory:output_type -> GetObjectHistoryResponse
	17, // 28: LineageStudioService.RefreshRepo:output_type -> RefreshRepoResponse
	19, // 29: LineageStudioService.VerifyObjectLineage:output_type -> VerifyObjectLineageResponse
	21, // 30: LineageStudioService.ChangeLineage:output_type -> ChangeLineageResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_lineage_studio_proto_init() }
func file_lineage_studio_proto_init() {
	if File_lineage_studio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lineage_studio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConflictDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReposRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReposResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRepoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRepoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyObjectLineageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyObjectLineageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeLineageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_studio_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeLineageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lineage_studio_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lineage_studio_proto_goTypes,
		DependencyIndexes: file_lineage_studio_proto_depIdxs,
		EnumInfos:         file_lineage_studio_proto_enumTypes,
		MessageInfos:      file_lineage_studio_proto_msgTypes,
	}.Build()
	File_lineage_studio_proto = out.File
	file_lineage_studio_proto_rawDesc = nil
	file_lineage_studio_proto_goTypes = nil
	file_lineage_studio_proto_depIdxs = nil
}
