// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: lineage-server.proto

package lineage_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJECT_TYPE_UNSPECIFIC ObjectType = 0
	ObjectType_OBJECT_TYPE_VIEW       ObjectType = 1
	ObjectType_OBJECT_TYPE_PROCEDURE  ObjectType = 2
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIC",
		1: "OBJECT_TYPE_VIEW",
		2: "OBJECT_TYPE_PROCEDURE",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIC": 0,
		"OBJECT_TYPE_VIEW":       1,
		"OBJECT_TYPE_PROCEDURE":  2,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_lineage_server_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_lineage_server_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_lineage_server_proto_rawDescGZIP(), []int{0}
}

type ObjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sql        string     `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	ObjectType ObjectType `protobuf:"varint,3,opt,name=object_type,json=objectType,proto3,enum=ObjectType" json:"object_type,omitempty"`
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_lineage_server_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectInfo) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ObjectInfo) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIC
}

type Lineage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target  string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Sources []string `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
}

func (x *Lineage) Reset() {
	*x = Lineage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lineage) ProtoMessage() {}

func (x *Lineage) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lineage.ProtoReflect.Descriptor instead.
func (*Lineage) Descriptor() ([]byte, []int) {
	return file_lineage_server_proto_rawDescGZIP(), []int{1}
}

func (x *Lineage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Lineage) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ObjectLineage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lineages []*Lineage `protobuf:"bytes,2,rep,name=lineages,proto3" json:"lineages,omitempty"`
}

func (x *ObjectLineage) Reset() {
	*x = ObjectLineage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectLineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLineage) ProtoMessage() {}

func (x *ObjectLineage) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLineage.ProtoReflect.Descriptor instead.
func (*ObjectLineage) Descriptor() ([]byte, []int) {
	return file_lineage_server_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectLineage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectLineage) GetLineages() []*Lineage {
	if x != nil {
		return x.Lineages
	}
	return nil
}

type LineageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*ObjectInfo `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *LineageRequest) Reset() {
	*x = LineageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageRequest) ProtoMessage() {}

func (x *LineageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageRequest.ProtoReflect.Descriptor instead.
func (*LineageRequest) Descriptor() ([]byte, []int) {
	return file_lineage_server_proto_rawDescGZIP(), []int{3}
}

func (x *LineageRequest) GetObjects() []*ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

type LineageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lineages []*ObjectLineage `protobuf:"bytes,1,rep,name=lineages,proto3" json:"lineages,omitempty"`
}

func (x *LineageResponse) Reset() {
	*x = LineageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageResponse) ProtoMessage() {}

func (x *LineageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageResponse.ProtoReflect.Descriptor instead.
func (*LineageResponse) Descriptor() ([]byte, []int) {
	return file_lineage_server_proto_rawDescGZIP(), []int{4}
}

func (x *LineageResponse) GetLineages() []*ObjectLineage {
	if x != nil {
		return x.Lineages
	}
	return nil
}

var File_lineage_server_proto protoreflect.FileDescriptor

var file_lineage_server_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x2c, 0x0a, 0x0b, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x07, 0x4c, 0x69, 0x6e, 0x65,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c,
	0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x6c, 0x69,
	0x6e, 0x65, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4c,
	0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x73,
	0x22, 0x37, 0x0a, 0x0e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x4c, 0x69, 0x6e,
	0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08,
	0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x59, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x43,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x42, 0x4a, 0x45,
	0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x44, 0x55, 0x52,
	0x45, 0x10, 0x02, 0x32, 0x41, 0x0a, 0x0e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65,
	0x61, 0x67, 0x65, 0x12, 0x0f, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lineage_server_proto_rawDescOnce sync.Once
	file_lineage_server_proto_rawDescData = file_lineage_server_proto_rawDesc
)

func file_lineage_server_proto_rawDescGZIP() []byte {
	file_lineage_server_proto_rawDescOnce.Do(func() {
		file_lineage_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_lineage_server_proto_rawDescData)
	})
	return file_lineage_server_proto_rawDescData
}

var file_lineage_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lineage_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lineage_server_proto_goTypes = []interface{}{
	(ObjectType)(0),         // 0: ObjectType
	(*ObjectInfo)(nil),      // 1: ObjectInfo
	(*Lineage)(nil),         // 2: Lineage
	(*ObjectLineage)(nil),   // 3: ObjectLineage
	(*LineageRequest)(nil),  // 4: LineageRequest
	(*LineageResponse)(nil), // 5: LineageResponse
}
var file_lineage_server_proto_depIdxs = []int32{
	0, // 0: ObjectInfo.object_type:type_name -> ObjectType
	2, // 1: ObjectLineage.lineages:type_name -> Lineage
	1, // 2: LineageRequest.objects:type_name -> ObjectInfo
	3, // 3: LineageResponse.lineages:type_name -> ObjectLineage
	4, // 4: LineageService.GetLineage:input_type -> LineageRequest
	5, // 5: LineageService.GetLineage:output_type -> LineageResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lineage_server_proto_init() }
func file_lineage_server_proto_init() {
	if File_lineage_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lineage_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lineage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectLineage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lineage_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lineage_server_proto_goTypes,
		DependencyIndexes: file_lineage_server_proto_depIdxs,
		EnumInfos:         file_lineage_server_proto_enumTypes,
		MessageInfos:      file_lineage_server_proto_msgTypes,
	}.Build()
	File_lineage_server_proto = out.File
	file_lineage_server_proto_rawDesc = nil
	file_lineage_server_proto_goTypes = nil
	file_lineage_server_proto_depIdxs = nil
}
