// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: lineage-studio.proto

package lineage_studioconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	lineage_studio "github.com/SunMaungOo/lineage-studio/internal/lineage-studio"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LineageStudioServiceName is the fully-qualified name of the LineageStudioService service.
	LineageStudioServiceName = "LineageStudioService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LineageStudioServiceGetReposProcedure is the fully-qualified name of the LineageStudioService's
	// GetRepos RPC.
	LineageStudioServiceGetReposProcedure = "/LineageStudioService/GetRepos"
	// LineageStudioServiceGetObjectsProcedure is the fully-qualified name of the LineageStudioService's
	// GetObjects RPC.
	LineageStudioServiceGetObjectsProcedure = "/LineageStudioService/GetObjects"
	// LineageStudioServiceGetObjectProcedure is the fully-qualified name of the LineageStudioService's
	// GetObject RPC.
	LineageStudioServiceGetObjectProcedure = "/LineageStudioService/GetObject"
	// LineageStudioServiceGetObjectHistoryProcedure is the fully-qualified name of the
	// LineageStudioService's GetObjectHistory RPC.
	LineageStudioServiceGetObjectHistoryProcedure = "/LineageStudioService/GetObjectHistory"
	// LineageStudioServiceRefreshRepoProcedure is the fully-qualified name of the
	// LineageStudioService's RefreshRepo RPC.
	LineageStudioServiceRefreshRepoProcedure = "/LineageStudioService/RefreshRepo"
	// LineageStudioServiceVerifyObjectLineageProcedure is the fully-qualified name of the
	// LineageStudioService's VerifyObjectLineage RPC.
	LineageStudioServiceVerifyObjectLineageProcedure = "/LineageStudioService/VerifyObjectLineage"
	// LineageStudioServiceChangeLineageProcedure is the fully-qualified name of the
	// LineageStudioService's ChangeLineage RPC.
	LineageStudioServiceChangeLineageProcedure = "/LineageStudioService/ChangeLineage"
)

// LineageStudioServiceClient is a client for the LineageStudioService service.
type LineageStudioServiceClient interface {
	// Get all repo summary
	GetRepos(context.Context, *connect.Request[lineage_studio.GetReposRequest]) (*connect.Response[lineage_studio.GetReposResponse], error)
	// Get all the object in the repo
	GetObjects(context.Context, *connect.Request[lineage_studio.GetObjectsRequest]) (*connect.Response[lineage_studio.GetObjectsResponse], error)
	// Get detail about single object in the repo
	GetObject(context.Context, *connect.Request[lineage_studio.GetObjectRequest]) (*connect.Response[lineage_studio.GetObjectResponse], error)
	// Get history timeline of single object in the repo
	GetObjectHistory(context.Context, *connect.Request[lineage_studio.GetObjectHistoryRequest]) (*connect.Response[lineage_studio.GetObjectHistoryResponse], error)
	RefreshRepo(context.Context, *connect.Request[lineage_studio.RefreshRepoRequest]) (*connect.Response[lineage_studio.RefreshRepoResponse], error)
	VerifyObjectLineage(context.Context, *connect.Request[lineage_studio.VerifyObjectLineageRequest]) (*connect.Response[lineage_studio.VerifyObjectLineageResponse], error)
	ChangeLineage(context.Context, *connect.Request[lineage_studio.ChangeLineageRequest]) (*connect.Response[lineage_studio.ChangeLineageResponse], error)
}

// NewLineageStudioServiceClient constructs a client for the LineageStudioService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLineageStudioServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LineageStudioServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lineageStudioServiceMethods := lineage_studio.File_lineage_studio_proto.Services().ByName("LineageStudioService").Methods()
	return &lineageStudioServiceClient{
		getRepos: connect.NewClient[lineage_studio.GetReposRequest, lineage_studio.GetReposResponse](
			httpClient,
			baseURL+LineageStudioServiceGetReposProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("GetRepos")),
			connect.WithClientOptions(opts...),
		),
		getObjects: connect.NewClient[lineage_studio.GetObjectsRequest, lineage_studio.GetObjectsResponse](
			httpClient,
			baseURL+LineageStudioServiceGetObjectsProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("GetObjects")),
			connect.WithClientOptions(opts...),
		),
		getObject: connect.NewClient[lineage_studio.GetObjectRequest, lineage_studio.GetObjectResponse](
			httpClient,
			baseURL+LineageStudioServiceGetObjectProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("GetObject")),
			connect.WithClientOptions(opts...),
		),
		getObjectHistory: connect.NewClient[lineage_studio.GetObjectHistoryRequest, lineage_studio.GetObjectHistoryResponse](
			httpClient,
			baseURL+LineageStudioServiceGetObjectHistoryProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("GetObjectHistory")),
			connect.WithClientOptions(opts...),
		),
		refreshRepo: connect.NewClient[lineage_studio.RefreshRepoRequest, lineage_studio.RefreshRepoResponse](
			httpClient,
			baseURL+LineageStudioServiceRefreshRepoProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("RefreshRepo")),
			connect.WithClientOptions(opts...),
		),
		verifyObjectLineage: connect.NewClient[lineage_studio.VerifyObjectLineageRequest, lineage_studio.VerifyObjectLineageResponse](
			httpClient,
			baseURL+LineageStudioServiceVerifyObjectLineageProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("VerifyObjectLineage")),
			connect.WithClientOptions(opts...),
		),
		changeLineage: connect.NewClient[lineage_studio.ChangeLineageRequest, lineage_studio.ChangeLineageResponse](
			httpClient,
			baseURL+LineageStudioServiceChangeLineageProcedure,
			connect.WithSchema(lineageStudioServiceMethods.ByName("ChangeLineage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lineageStudioServiceClient implements LineageStudioServiceClient.
type lineageStudioServiceClient struct {
	getRepos            *connect.Client[lineage_studio.GetReposRequest, lineage_studio.GetReposResponse]
	getObjects          *connect.Client[lineage_studio.GetObjectsRequest, lineage_studio.GetObjectsResponse]
	getObject           *connect.Client[lineage_studio.GetObjectRequest, lineage_studio.GetObjectResponse]
	getObjectHistory    *connect.Client[lineage_studio.GetObjectHistoryRequest, lineage_studio.GetObjectHistoryResponse]
	refreshRepo         *connect.Client[lineage_studio.RefreshRepoRequest, lineage_studio.RefreshRepoResponse]
	verifyObjectLineage *connect.Client[lineage_studio.VerifyObjectLineageRequest, lineage_studio.VerifyObjectLineageResponse]
	changeLineage       *connect.Client[lineage_studio.ChangeLineageRequest, lineage_studio.ChangeLineageResponse]
}

// GetRepos calls LineageStudioService.GetRepos.
func (c *lineageStudioServiceClient) GetRepos(ctx context.Context, req *connect.Request[lineage_studio.GetReposRequest]) (*connect.Response[lineage_studio.GetReposResponse], error) {
	return c.getRepos.CallUnary(ctx, req)
}

// GetObjects calls LineageStudioService.GetObjects.
func (c *lineageStudioServiceClient) GetObjects(ctx context.Context, req *connect.Request[lineage_studio.GetObjectsRequest]) (*connect.Response[lineage_studio.GetObjectsResponse], error) {
	return c.getObjects.CallUnary(ctx, req)
}

// GetObject calls LineageStudioService.GetObject.
func (c *lineageStudioServiceClient) GetObject(ctx context.Context, req *connect.Request[lineage_studio.GetObjectRequest]) (*connect.Response[lineage_studio.GetObjectResponse], error) {
	return c.getObject.CallUnary(ctx, req)
}

// GetObjectHistory calls LineageStudioService.GetObjectHistory.
func (c *lineageStudioServiceClient) GetObjectHistory(ctx context.Context, req *connect.Request[lineage_studio.GetObjectHistoryRequest]) (*connect.Response[lineage_studio.GetObjectHistoryResponse], error) {
	return c.getObjectHistory.CallUnary(ctx, req)
}

// RefreshRepo calls LineageStudioService.RefreshRepo.
func (c *lineageStudioServiceClient) RefreshRepo(ctx context.Context, req *connect.Request[lineage_studio.RefreshRepoRequest]) (*connect.Response[lineage_studio.RefreshRepoResponse], error) {
	return c.refreshRepo.CallUnary(ctx, req)
}

// VerifyObjectLineage calls LineageStudioService.VerifyObjectLineage.
func (c *lineageStudioServiceClient) VerifyObjectLineage(ctx context.Context, req *connect.Request[lineage_studio.VerifyObjectLineageRequest]) (*connect.Response[lineage_studio.VerifyObjectLineageResponse], error) {
	return c.verifyObjectLineage.CallUnary(ctx, req)
}

// ChangeLineage calls LineageStudioService.ChangeLineage.
func (c *lineageStudioServiceClient) ChangeLineage(ctx context.Context, req *connect.Request[lineage_studio.ChangeLineageRequest]) (*connect.Response[lineage_studio.ChangeLineageResponse], error) {
	return c.changeLineage.CallUnary(ctx, req)
}

// LineageStudioServiceHandler is an implementation of the LineageStudioService service.
type LineageStudioServiceHandler interface {
	// Get all repo summary
	GetRepos(context.Context, *connect.Request[lineage_studio.GetReposRequest]) (*connect.Response[lineage_studio.GetReposResponse], error)
	// Get all the object in the repo
	GetObjects(context.Context, *connect.Request[lineage_studio.GetObjectsRequest]) (*connect.Response[lineage_studio.GetObjectsResponse], error)
	// Get detail about single object in the repo
	GetObject(context.Context, *connect.Request[lineage_studio.GetObjectRequest]) (*connect.Response[lineage_studio.GetObjectResponse], error)
	// Get history timeline of single object in the repo
	GetObjectHistory(context.Context, *connect.Request[lineage_studio.GetObjectHistoryRequest]) (*connect.Response[lineage_studio.GetObjectHistoryResponse], error)
	RefreshRepo(context.Context, *connect.Request[lineage_studio.RefreshRepoRequest]) (*connect.Response[lineage_studio.RefreshRepoResponse], error)
	VerifyObjectLineage(context.Context, *connect.Request[lineage_studio.VerifyObjectLineageRequest]) (*connect.Response[lineage_studio.VerifyObjectLineageResponse], error)
	ChangeLineage(context.Context, *connect.Request[lineage_studio.ChangeLineageRequest]) (*connect.Response[lineage_studio.ChangeLineageResponse], error)
}

// NewLineageStudioServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLineageStudioServiceHandler(svc LineageStudioServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lineageStudioServiceMethods := lineage_studio.File_lineage_studio_proto.Services().ByName("LineageStudioService").Methods()
	lineageStudioServiceGetReposHandler := connect.NewUnaryHandler(
		LineageStudioServiceGetReposProcedure,
		svc.GetRepos,
		connect.WithSchema(lineageStudioServiceMethods.ByName("GetRepos")),
		connect.WithHandlerOptions(opts...),
	)
	lineageStudioServiceGetObjectsHandler := connect.NewUnaryHandler(
		LineageStudioServiceGetObjectsProcedure,
		svc.GetObjects,
		connect.WithSchema(lineageStudioServiceMethods.ByName("GetObjects")),
		connect.WithHandlerOptions(opts...),
	)
	lineageStudioServiceGetObjectHandler := connect.NewUnaryHandler(
		LineageStudioServiceGetObjectProcedure,
		svc.GetObject,
		connect.WithSchema(lineageStudioServiceMethods.ByName("GetObject")),
		connect.WithHandlerOptions(opts...),
	)
	lineageStudioServiceGetObjectHistoryHandler := connect.NewUnaryHandler(
		LineageStudioServiceGetObjectHistoryProcedure,
		svc.GetObjectHistory,
		connect.WithSchema(lineageStudioServiceMethods.ByName("GetObjectHistory")),
		connect.WithHandlerOptions(opts...),
	)
	lineageStudioServiceRefreshRepoHandler := connect.NewUnaryHandler(
		LineageStudioServiceRefreshRepoProcedure,
		svc.RefreshRepo,
		connect.WithSchema(lineageStudioServiceMethods.ByName("RefreshRepo")),
		connect.WithHandlerOptions(opts...),
	)
	lineageStudioServiceVerifyObjectLineageHandler := connect.NewUnaryHandler(
		LineageStudioServiceVerifyObjectLineageProcedure,
		svc.VerifyObjectLineage,
		connect.WithSchema(lineageStudioServiceMethods.ByName("VerifyObjectLineage")),
		connect.WithHandlerOptions(opts...),
	)
	lineageStudioServiceChangeLineageHandler := connect.NewUnaryHandler(
		LineageStudioServiceChangeLineageProcedure,
		svc.ChangeLineage,
		connect.WithSchema(lineageStudioServiceMethods.ByName("ChangeLineage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/LineageStudioService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LineageStudioServiceGetReposProcedure:
			lineageStudioServiceGetReposHandler.ServeHTTP(w, r)
		case LineageStudioServiceGetObjectsProcedure:
			lineageStudioServiceGetObjectsHandler.ServeHTTP(w, r)
		case LineageStudioServiceGetObjectProcedure:
			lineageStudioServiceGetObjectHandler.ServeHTTP(w, r)
		case LineageStudioServiceGetObjectHistoryProcedure:
			lineageStudioServiceGetObjectHistoryHandler.ServeHTTP(w, r)
		case LineageStudioServiceRefreshRepoProcedure:
			lineageStudioServiceRefreshRepoHandler.ServeHTTP(w, r)
		case LineageStudioServiceVerifyObjectLineageProcedure:
			lineageStudioServiceVerifyObjectLineageHandler.ServeHTTP(w, r)
		case LineageStudioServiceChangeLineageProcedure:
			lineageStudioServiceChangeLineageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLineageStudioServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLineageStudioServiceHandler struct{}

func (UnimplementedLineageStudioServiceHandler) GetRepos(context.Context, *connect.Request[lineage_studio.GetReposRequest]) (*connect.Response[lineage_studio.GetReposResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.GetRepos is not implemented"))
}

func (UnimplementedLineageStudioServiceHandler) GetObjects(context.Context, *connect.Request[lineage_studio.GetObjectsRequest]) (*connect.Response[lineage_studio.GetObjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.GetObjects is not implemented"))
}

func (UnimplementedLineageStudioServiceHandler) GetObject(context.Context, *connect.Request[lineage_studio.GetObjectRequest]) (*connect.Response[lineage_studio.GetObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.GetObject is not implemented"))
}

func (UnimplementedLineageStudioServiceHandler) GetObjectHistory(context.Context, *connect.Request[lineage_studio.GetObjectHistoryRequest]) (*connect.Response[lineage_studio.GetObjectHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.GetObjectHistory is not implemented"))
}

func (UnimplementedLineageStudioServiceHandler) RefreshRepo(context.Context, *connect.Request[lineage_studio.RefreshRepoRequest]) (*connect.Response[lineage_studio.RefreshRepoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.RefreshRepo is not implemented"))
}

func (UnimplementedLineageStudioServiceHandler) VerifyObjectLineage(context.Context, *connect.Request[lineage_studio.VerifyObjectLineageRequest]) (*connect.Response[lineage_studio.VerifyObjectLineageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.VerifyObjectLineage is not implemented"))
}

func (UnimplementedLineageStudioServiceHandler) ChangeLineage(context.Context, *connect.Request[lineage_studio.ChangeLineageRequest]) (*connect.Response[lineage_studio.ChangeLineageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageStudioService.ChangeLineage is not implemented"))
}
