// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: lineage-explorer.proto

package lineage_explorer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LineageStatus int32

const (
	LineageStatus_LINEAGE_STATUS_UNSPECIFIED LineageStatus = 0
	LineageStatus_LINEAGE_STATUS_OK          LineageStatus = 1
	LineageStatus_LINEAGE_STATUS_NO_CHANGES  LineageStatus = 2
	LineageStatus_LINEAGE_STATUS_ERROR       LineageStatus = 3
)

// Enum value maps for LineageStatus.
var (
	LineageStatus_name = map[int32]string{
		0: "LINEAGE_STATUS_UNSPECIFIED",
		1: "LINEAGE_STATUS_OK",
		2: "LINEAGE_STATUS_NO_CHANGES",
		3: "LINEAGE_STATUS_ERROR",
	}
	LineageStatus_value = map[string]int32{
		"LINEAGE_STATUS_UNSPECIFIED": 0,
		"LINEAGE_STATUS_OK":          1,
		"LINEAGE_STATUS_NO_CHANGES":  2,
		"LINEAGE_STATUS_ERROR":       3,
	}
)

func (x LineageStatus) Enum() *LineageStatus {
	p := new(LineageStatus)
	*p = x
	return p
}

func (x LineageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lineage_explorer_proto_enumTypes[0].Descriptor()
}

func (LineageStatus) Type() protoreflect.EnumType {
	return &file_lineage_explorer_proto_enumTypes[0]
}

func (x LineageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineageStatus.Descriptor instead.
func (LineageStatus) EnumDescriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{0}
}

type RepoSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DatabaseType string `protobuf:"bytes,2,opt,name=database_type,json=databaseType,proto3" json:"database_type,omitempty"`
	Host         string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	DbName       string `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	RepoVersion  string `protobuf:"bytes,5,opt,name=repo_version,json=repoVersion,proto3" json:"repo_version,omitempty"`
}

func (x *RepoSummary) Reset() {
	*x = RepoSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoSummary) ProtoMessage() {}

func (x *RepoSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoSummary.ProtoReflect.Descriptor instead.
func (*RepoSummary) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *RepoSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepoSummary) GetDatabaseType() string {
	if x != nil {
		return x.DatabaseType
	}
	return ""
}

func (x *RepoSummary) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RepoSummary) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *RepoSummary) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

type GetReposRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReposRequest) Reset() {
	*x = GetReposRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposRequest) ProtoMessage() {}

func (x *GetReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposRequest.ProtoReflect.Descriptor instead.
func (*GetReposRequest) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{1}
}

type GetReposResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repos []*RepoSummary `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
}

func (x *GetReposResponse) Reset() {
	*x = GetReposResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposResponse) ProtoMessage() {}

func (x *GetReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposResponse.ProtoReflect.Descriptor instead.
func (*GetReposResponse) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *GetReposResponse) GetRepos() []*RepoSummary {
	if x != nil {
		return x.Repos
	}
	return nil
}

type Statement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []string `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Target  string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *Statement) Reset() {
	*x = Statement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{3}
}

func (x *Statement) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Statement) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type LineageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoVersion string           `protobuf:"bytes,1,opt,name=repoVersion,proto3" json:"repoVersion,omitempty"`
	Details     []*LineageDetail `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	Status      LineageStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=LineageStatus" json:"status,omitempty"`
}

func (x *LineageResponse) Reset() {
	*x = LineageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageResponse) ProtoMessage() {}

func (x *LineageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageResponse.ProtoReflect.Descriptor instead.
func (*LineageResponse) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{4}
}

func (x *LineageResponse) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

func (x *LineageResponse) GetDetails() []*LineageDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *LineageResponse) GetStatus() LineageStatus {
	if x != nil {
		return x.Status
	}
	return LineageStatus_LINEAGE_STATUS_UNSPECIFIED
}

type LineageDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo       string       `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type       string       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Statements []*Statement `protobuf:"bytes,4,rep,name=statements,proto3" json:"statements,omitempty"`
}

func (x *LineageDetail) Reset() {
	*x = LineageDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageDetail) ProtoMessage() {}

func (x *LineageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageDetail.ProtoReflect.Descriptor instead.
func (*LineageDetail) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{5}
}

func (x *LineageDetail) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *LineageDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LineageDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LineageDetail) GetStatements() []*Statement {
	if x != nil {
		return x.Statements
	}
	return nil
}

type LineageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoName    string `protobuf:"bytes,1,opt,name=repoName,proto3" json:"repoName,omitempty"`
	RepoVersion string `protobuf:"bytes,2,opt,name=repoVersion,proto3" json:"repoVersion,omitempty"`
}

func (x *LineageRequest) Reset() {
	*x = LineageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineage_explorer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageRequest) ProtoMessage() {}

func (x *LineageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lineage_explorer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageRequest.ProtoReflect.Descriptor instead.
func (*LineageRequest) Descriptor() ([]byte, []int) {
	return file_lineage_explorer_proto_rawDescGZIP(), []int{6}
}

func (x *LineageRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *LineageRequest) GetRepoVersion() string {
	if x != nil {
		return x.RepoVersion
	}
	return ""
}

var File_lineage_explorer_proto protoreflect.FileDescriptor

var file_lineage_explorer_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x2d, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70,
	0x6f, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x22, 0x3d, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0f,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4c, 0x69,
	0x6e, 0x65, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x77, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4e, 0x0a, 0x0e,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x70, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0x7f, 0x0a, 0x0d,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a,
	0x1a, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x4f, 0x4b, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x47, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x53, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x47, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x32, 0x73, 0x0a,
	0x0f, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72,
	0x12, 0x2f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x12, 0x10, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x12,
	0x0f, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lineage_explorer_proto_rawDescOnce sync.Once
	file_lineage_explorer_proto_rawDescData = file_lineage_explorer_proto_rawDesc
)

func file_lineage_explorer_proto_rawDescGZIP() []byte {
	file_lineage_explorer_proto_rawDescOnce.Do(func() {
		file_lineage_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(file_lineage_explorer_proto_rawDescData)
	})
	return file_lineage_explorer_proto_rawDescData
}

var file_lineage_explorer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lineage_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lineage_explorer_proto_goTypes = []interface{}{
	(LineageStatus)(0),       // 0: LineageStatus
	(*RepoSummary)(nil),      // 1: RepoSummary
	(*GetReposRequest)(nil),  // 2: GetReposRequest
	(*GetReposResponse)(nil), // 3: GetReposResponse
	(*Statement)(nil),        // 4: Statement
	(*LineageResponse)(nil),  // 5: LineageResponse
	(*LineageDetail)(nil),    // 6: LineageDetail
	(*LineageRequest)(nil),   // 7: LineageRequest
}
var file_lineage_explorer_proto_depIdxs = []int32{
	1, // 0: GetReposResponse.repos:type_name -> RepoSummary
	6, // 1: LineageResponse.details:type_name -> LineageDetail
	0, // 2: LineageResponse.status:type_name -> LineageStatus
	4, // 3: LineageDetail.statements:type_name -> Statement
	2, // 4: LineageExplorer.GetRepos:input_type -> GetReposRequest
	7, // 5: LineageExplorer.GetLineage:input_type -> LineageRequest
	3, // 6: LineageExplorer.GetRepos:output_type -> GetReposResponse
	5, // 7: LineageExplorer.GetLineage:output_type -> LineageResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lineage_explorer_proto_init() }
func file_lineage_explorer_proto_init() {
	if File_lineage_explorer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lineage_explorer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_explorer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReposRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_explorer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReposResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_explorer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_explorer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_explorer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineageDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineage_explorer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lineage_explorer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lineage_explorer_proto_goTypes,
		DependencyIndexes: file_lineage_explorer_proto_depIdxs,
		EnumInfos:         file_lineage_explorer_proto_enumTypes,
		MessageInfos:      file_lineage_explorer_proto_msgTypes,
	}.Build()
	File_lineage_explorer_proto = out.File
	file_lineage_explorer_proto_rawDesc = nil
	file_lineage_explorer_proto_goTypes = nil
	file_lineage_explorer_proto_depIdxs = nil
}
