// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: lineage-explorer.proto

package lineage_explorerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	lineage_explorer "github.com/SunMaungOo/lineage-studio/internal/lineage-explorer"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LineageExplorerName is the fully-qualified name of the LineageExplorer service.
	LineageExplorerName = "LineageExplorer"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LineageExplorerGetReposProcedure is the fully-qualified name of the LineageExplorer's GetRepos
	// RPC.
	LineageExplorerGetReposProcedure = "/LineageExplorer/GetRepos"
	// LineageExplorerGetLineageProcedure is the fully-qualified name of the LineageExplorer's
	// GetLineage RPC.
	LineageExplorerGetLineageProcedure = "/LineageExplorer/GetLineage"
)

// LineageExplorerClient is a client for the LineageExplorer service.
type LineageExplorerClient interface {
	GetRepos(context.Context, *connect.Request[lineage_explorer.GetReposRequest]) (*connect.Response[lineage_explorer.GetReposResponse], error)
	GetLineage(context.Context, *connect.Request[lineage_explorer.LineageRequest]) (*connect.Response[lineage_explorer.LineageResponse], error)
}

// NewLineageExplorerClient constructs a client for the LineageExplorer service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLineageExplorerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LineageExplorerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lineageExplorerMethods := lineage_explorer.File_lineage_explorer_proto.Services().ByName("LineageExplorer").Methods()
	return &lineageExplorerClient{
		getRepos: connect.NewClient[lineage_explorer.GetReposRequest, lineage_explorer.GetReposResponse](
			httpClient,
			baseURL+LineageExplorerGetReposProcedure,
			connect.WithSchema(lineageExplorerMethods.ByName("GetRepos")),
			connect.WithClientOptions(opts...),
		),
		getLineage: connect.NewClient[lineage_explorer.LineageRequest, lineage_explorer.LineageResponse](
			httpClient,
			baseURL+LineageExplorerGetLineageProcedure,
			connect.WithSchema(lineageExplorerMethods.ByName("GetLineage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lineageExplorerClient implements LineageExplorerClient.
type lineageExplorerClient struct {
	getRepos   *connect.Client[lineage_explorer.GetReposRequest, lineage_explorer.GetReposResponse]
	getLineage *connect.Client[lineage_explorer.LineageRequest, lineage_explorer.LineageResponse]
}

// GetRepos calls LineageExplorer.GetRepos.
func (c *lineageExplorerClient) GetRepos(ctx context.Context, req *connect.Request[lineage_explorer.GetReposRequest]) (*connect.Response[lineage_explorer.GetReposResponse], error) {
	return c.getRepos.CallUnary(ctx, req)
}

// GetLineage calls LineageExplorer.GetLineage.
func (c *lineageExplorerClient) GetLineage(ctx context.Context, req *connect.Request[lineage_explorer.LineageRequest]) (*connect.Response[lineage_explorer.LineageResponse], error) {
	return c.getLineage.CallUnary(ctx, req)
}

// LineageExplorerHandler is an implementation of the LineageExplorer service.
type LineageExplorerHandler interface {
	GetRepos(context.Context, *connect.Request[lineage_explorer.GetReposRequest]) (*connect.Response[lineage_explorer.GetReposResponse], error)
	GetLineage(context.Context, *connect.Request[lineage_explorer.LineageRequest]) (*connect.Response[lineage_explorer.LineageResponse], error)
}

// NewLineageExplorerHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLineageExplorerHandler(svc LineageExplorerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lineageExplorerMethods := lineage_explorer.File_lineage_explorer_proto.Services().ByName("LineageExplorer").Methods()
	lineageExplorerGetReposHandler := connect.NewUnaryHandler(
		LineageExplorerGetReposProcedure,
		svc.GetRepos,
		connect.WithSchema(lineageExplorerMethods.ByName("GetRepos")),
		connect.WithHandlerOptions(opts...),
	)
	lineageExplorerGetLineageHandler := connect.NewUnaryHandler(
		LineageExplorerGetLineageProcedure,
		svc.GetLineage,
		connect.WithSchema(lineageExplorerMethods.ByName("GetLineage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/LineageExplorer/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LineageExplorerGetReposProcedure:
			lineageExplorerGetReposHandler.ServeHTTP(w, r)
		case LineageExplorerGetLineageProcedure:
			lineageExplorerGetLineageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLineageExplorerHandler returns CodeUnimplemented from all methods.
type UnimplementedLineageExplorerHandler struct{}

func (UnimplementedLineageExplorerHandler) GetRepos(context.Context, *connect.Request[lineage_explorer.GetReposRequest]) (*connect.Response[lineage_explorer.GetReposResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageExplorer.GetRepos is not implemented"))
}

func (UnimplementedLineageExplorerHandler) GetLineage(context.Context, *connect.Request[lineage_explorer.LineageRequest]) (*connect.Response[lineage_explorer.LineageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("LineageExplorer.GetLineage is not implemented"))
}
