# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lineage_server_pb2 as lineage__server__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lineage_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LineageServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLineage = channel.unary_unary(
                '/LineageService/GetLineage',
                request_serializer=lineage__server__pb2.LineageRequest.SerializeToString,
                response_deserializer=lineage__server__pb2.LineageResponse.FromString,
                _registered_method=True)


class LineageServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetLineage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LineageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLineage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLineage,
                    request_deserializer=lineage__server__pb2.LineageRequest.FromString,
                    response_serializer=lineage__server__pb2.LineageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LineageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LineageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LineageService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLineage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LineageService/GetLineage',
            lineage__server__pb2.LineageRequest.SerializeToString,
            lineage__server__pb2.LineageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
